### ISSUE TITLE
Sivas Sami Aydın Tüneli

### ISSUE THREAD

**Issue by sivasspor** [osmlab/appledata#143]
A new tunnel was opened in Sivas, but not on Apple Maps.

https://goo.gl/maps/68mvdtFL7Pk

**Comment by tohaklim** [comment]
You’re probably better off reporting this through the Maps.app feedback mechanism. And provide links to osm instead of google, considering the name of the repo

**Comment by awisemanapple** [comment]
Thanks for the feedback! And yes, please report the problem through the Maps app also.

**Comment by sivasspor** [comment]
I've made feedback many times over maps application, but not yet shown  on map. I shared the Google Maps link because the tunnel is not in OSM.
