### ISSUE TITLE
how do we recognize edits as belonging to Apple's efforts?

### ISSUE THREAD

**Issue by mfrasca** [osmlab/appledata#159]
You seem to have decided not to require your editors to declare their changesets being part of this Apple effort.  In this situation the only indication that a changeset belongs to your team is the jumping behaviour of your editors (3 corrections in Guatemala, one in Ecuador, then Dominican Republic, then back to Central America …).  To make the challenge more complete, in your data team composition you only declare the current affiliation, not its history.  

What do you think you could do, to make things more simple for external reviewers?  We all want a better map, and we all cope with limited resources, so simplicity ought to be in everybody's interest.

**Comment by awisemanapple** [comment]
Hi Mario. We take several steps to reach out to local communities before we begin mapping and we are diligent in responding to and communicating with the community as we go along. It is our goal to work with local communities and everyone to build the best map possible. We always post on the community’s main communications channels that we’ll be mapping and ask for feedback. 

About a year ago I posted on the Panama OSM Forum and linked to our Panama project Github page: https://forum.openstreetmap.org/viewforum.php?id=61 and also reached out directly to a few active editors in Panama in early 2018 via OSM DMs. (This was before the Panama Telegram existed.) I also did a Skype call a few years ago with a community member I met at SOTM Latam in Santiago who did a presentation there about OSM Panama. As you suggested, I posted on the Telegram and added a link to our Panama project Github page on the OSM wiki for Panama. I also posted earlier on Telegram about the Panama MapRoulette challenges I made (https://maproulette.org/browse/projects/38877). We list every project we are doing on the OSM wiki under the Organized Activities page, which is also linked from the OSM wiki page for Apple and our Github. People can also contact me directly with any questions, my OSM username (andrewwiseman) is linked on every Github issue and on our Organized Editing page on the OSM wiki.

Like you noted, every member of our team has their affiliation listed on their OSM profile with a link to our Github and we have a list of all the members of our team on our Github. There are multiple tools out there for tracking mappers such as OSMCha, OSM Teams and others. Here’s OSMCha set up to track me, for example: https://osmcha.org/?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22andrewwiseman%22%2C%22value%22%3A%22andrewwiseman%22%7D%5D%7D and here’s OSM Teams: https://dev.mapping.team. There was a presentation about this at the academic track of SOTM last year too: https://2019.stateofthemap.org/sessions/W8BA9K/. Hope this helps.

**Comment by mfrasca** [comment]
all you wrote above was already well known, and no, it does not help.

**Comment by vinber** [comment]
why don't you use #appleteam or something like that ?

**Comment by Marc-marc-marc** [comment]
there is a guide for directed contributions of which the one you are talking about seems to be a part. it seems to me that at the very least a correct profile that at least informs the group is a good prattice. unique hashtag too.
https://wiki.openstreetmap.org/wiki/Organised_Editing
https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines

**Comment by johnwhelan** [comment]
It does make life easier to provide appropriate feedback if you tag they are part of Apple.  I note some of your editors have been reclassifying highways away from the classifications documented for African highways in the wiki for example.

**Comment by mfrasca** [comment]
wondering … who keeps track of the "Community Objections" column in the [Activities overview](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities)?  

I have complained for this team's edits in Panamá, and after a couple of incidents, they keep clear of the country, but I see they also avoid Nicaragua, Haiti, Colombia.  

yet, the corresponding "Community Objections" cell states "None".

**Comment by matkoniecz** [comment]
> wondering … who keeps track of the "Community Objections" column in the Activities overview?

Looking at https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines#Possible_actions_on_problematic_edits - they are not obligated to do this

Given that it is wiki and they are not doing it on their own - feel free to edit it on your own

**Comment by matkoniecz** [comment]
See https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines#Possible_actions_on_problematic_edits

> Changeset comments should include the unique hashtag described on the wiki page under Organised Editing/Activities/Name of the Activity (as described in the Process section), and link to that page.

**Comment by vinber** [comment]
@awisemanapple could you reopen this issue please ?

**Comment by matkoniecz** [comment]
Note, in case of Organised Editing Guidelines getting ignored what results in harmful effects, mappers may contact DWG ( https://wiki.openstreetmap.org/wiki/Data_working_group ).

DWG may repeat request, explain in more detail. DWG may also block/ban users and revert edits.

**Comment by awisemanapple** [comment]
Thanks for the comments, we are talking about what we can do.

**Comment by mfrasca** [comment]
a couple of things that have been mentioned in https://t.me/OpenStreetMapOrg:
- make sure your team uses the `#apple` hashtag to their changesets
- that we require a tag on the changeset such as `organised_by=[apple|kaart|amazonlogistics]`
- my own hint was having your team members use a OSM account name that starts with `apple-` — a lot less work for you, if that's the problem.

**Comment by matkoniecz** [comment]
To clarify, `organised_by` changeset tag is a a good idea but it is not mandatory. 

But hashtag in changeset comments is mandatory.

> Changeset comments should include the unique hashtag described on the wiki page under Organised Editing/Activities/Name of the Activity (as described in the Process section), and link to that page.

**Comment by mfrasca** [comment]
> Thanks for the comments, we are talking about what we can do.

ping

**Comment by awisemanapple** [comment]
Hi Mario. We talked to DWG earlier this week and are working on a plan for a hashtag. Stay tuned.

**Comment by mfrasca** [comment]
"we are working on a plan for a hashtag" … you make it sound difficult.
if you can't use `#apple`, what about `#iTag`?

**Comment by Marc-marc-marc** [comment]
https://www.openstreetmap.org/changeset/85082006
not much improvement 2 months after my previous message. 
it's not serious for something as simple as putting a hashtag on the changeset !
I have therefore made the issue visible on the "Activities" page.
next step : be happy to see that you act concretely on this request or raise it

**Comment by matkoniecz** [comment]
in case of Organised Editing Guidelines getting ignored what results in harmful effects, mappers may contact DWG ( https://wiki.openstreetmap.org/wiki/Data_working_group ).

DWG may repeat request, explain in more detail. DWG may also block/ban users and revert edits.

In this specific case I am not affected and there is no damage of OSM data, so I am not planning to complain. But if someone is affected...

**Comment by awisemanapple** [comment]
Thanks for the comments. Our team is all working from their homes these days, so we want to make sure anything we do is consistent and accurate. We have been looking for technical solutions, if that is not possible we will be adjusting our workflows. Stay tuned.

**Comment by mfrasca** [comment]
Andrew, can you make us understand your (corporate) difficulties with 
simply requesting your mappers to add a "apple" tag to their changesets?

**Comment by mfrasca** [comment]
@matkoniecz 
> In this specific case I am not affected and there is no damage of OSM data, so I am not planning to complain. But if someone is affected...

please note: Apple edits are difficult to spot as coming from Apple organization, so if we're affected, like we have been in Panama —and @johnwhelan mentions highways in Africa—, we complain with an individual, not realizing it's part of this organization.

so, even if you might not be affected, and even if Apple's behaviour doesn't help recognizing their work as theirs, there's been people damaged enough to investigate the case and discover they were dealing with Apple.

I completely fail to understand what's the big deal, making your edits recognizable.

**Comment by awisemanapple** [comment]
Thanks for the comments everyone. Our team is using the hashtag #adt (for Apple Data Team) and our Github page and Organized Editing page have been updated to reflect that.

**Comment by vinber** [comment]
Hi, thank for your #adt but i think it's too short, for example for Neis map http://resultmaps.neis-one.org/osm-changesets?comment=apple#2/7.4/27.1

It's at least 5 characters !

**Comment by pa5cal** [comment]
Should work now: https://resultmaps.neis-one.org/osm-changesets?comment=adt

**Comment by vinber** [comment]
thank you very much @pa5cal 

however i think 3 characters is too short for a so important hastag -> why it's not #appledatateam ? it's simple et clearer

**Comment by matkoniecz** [comment]
And meaning is not hidden/obscured.

**Comment by mfrasca** [comment]
https://en.wikipedia.org/wiki/ADT
I guess it's unique at least within OSM.
(nope, it's Android Development Tools).
anyhow, it took 3 months for Apple to take this decision, I would not dare asking them to think better.

**Comment by mfrasca** [comment]
> Should work now for the mentioned hashtag #adt
> https://resultmaps.neis-one.org/osm-changesets?comment=adt

I don't know if you would make an exception just for `adt`, or fix the explanation "(min. 5 and max. 32 characters)"

**Comment by vinber** [comment]
>  anyhow, it took 3 months for Apple to take this decision, I would not dare asking them to think better.

i think we must ask them to think better.

so @awisemanapple can you try a better hastag, at least 5 characters, unique, ... Suggestion #appledatateam ?

**Comment by awisemanapple** [comment]
Thanks for the comment, we prefer to use #adt.  We communicated the use of this hashtag here and by adding it to our organised editing page (https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Apple) like the guidelines suggest, as well as to our all project pages on Github, the front page of this Github and on the OSM user page for each of our editors.
