### ISSUE TITLE
Atypical Colombian changes by new users

### ISSUE THREAD

**Issue by angoca** [osmlab/appledata#166]
Hi, I have found several new users performing modifications in some areas in Colombia, that are not very popular places. All users have atypical names, profile pictures, and a common text making reference that they belong to the Apple Data Team. All commits also use the hashtag #adt, and no one from the Colombian community is aware of or recognizes this initiative, in that particular area.

The users were created the same day, and they are:

- StrzeleckiDesert
- LakeKutcharo
- Ahaggarplateau
- LittleScarciesRiver
- MontHiuchigatake

I would like to know if these users are really part of the Apple Data Team? and if they are what are they going to map? This is to be aware of the current activities in the country.

**Comment by awisemanapple** [comment]
@angoca Hi Andres, thanks for the comment, and we also saw the welcome messages those mappers received, thank you for those. (Also you and I met a few years ago in Bogotá at a mapathon you organized!) Yes, these are Apple mappers who joined the team recently, I have added them to our username list here on our Github and on the OSM WIki. 

They are working on adding missing roads and adjusting existing roads as needed, such as correcting alignment or fixing any issues like missing connections or overlapping ways, which is part of the Colombia data improvements project described here https://github.com/osmlab/appledata/issues/43. 

If you have any questions or concerns about specific edits, please comment on the changesets or send the mappers a direct message on OSM, or you can email me ([andrew_wiseman@apple.com](mailto:andrew_wiseman@apple.com)) or send me a direct message too. Github comments are fine as well, but changeset comments can be easiest if they are related to a specific edit. I hope this helps, thanks!
