### ISSUE TITLE
Stop "aligning" roads in Madeira island, Portugal

### ISSUE THREAD

**Issue by iamnunocaldeira** [osmlab/appledata#167]
Please read this for future edits, asi already explained last year and once again Apple is doing the same mistake. Further details explained in this changeset comment https://www.openstreetmap.org/changeset/121468048#map=17/32.73445/-17.19723

**Comment by awisemanapple** [comment]
Hello Nuno, thanks for the comment. We have seen the changeset comments and have responded and addressed it. 

In addition, it looks like the IRIG imagery you mentioned before (https://irig-geoportal.madeira.gov.pt/IRIGWMS_OI_Ortofotomapas2018/Service.svc/get?request=GetCapabilities&service=WMS&VERSION=1.3.0) and that was in the changeset comment is not in the JOSM default providers, would it be possible to add it to the preferred imagery list at https://josm.openstreetmap.de/wiki/Maps ?

**Comment by awisemanapple** [comment]
I believe this issue is resolved, closing.
